# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 21:53
from __future__ import unicode_literals

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questionnaire', '__first__'),
        ('patient', '__first__'),
        ('secretariat', '__first__'),
        ('healthprofessional', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='RCMessage',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('subject',
                 core.models.EncryptedCharField(max_length=1024,
                                                verbose_name='Onderwerp')),
                ('internal_message', core.models.EncryptedTextField(
                    blank=True, null=True)),
                ('added_on', models.DateField(auto_now_add=True)),
                ('read_on', models.DateField(blank=True, null=True)),
                ('healthprofessional',
                 models.ForeignKey(blank=True,
                                   null=True,
                                   on_delete=django.db.models.deletion.CASCADE,
                                   to='healthprofessional.HealthProfessional')),
                ('patient',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='patient.Patient')),
                ('related_to',
                 models.ForeignKey(null=True,
                                   on_delete=django.db.models.deletion.CASCADE,
                                   to='questionnaire.QuestionnaireRequest')),
                ('secretary',
                 models.ForeignKey(blank=True,
                                   null=True,
                                   on_delete=django.db.models.deletion.CASCADE,
                                   to='secretariat.Secretary')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, core.models.ModelAuditMixin),
        ),
    ]
