# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 21:53
from __future__ import unicode_literals

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questionnaire', '__first__'),
        ('healthprofessional', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('finished_on', models.DateField(blank=True, null=True)),
                ('invalid', models.BooleanField(default=False)),
                ('sent_to_doctor',
                 models.BooleanField(default=False,
                                     verbose_name='Na opslaan naar huisarts sturen')),
                (
                    'patient_needs_appointment',
                    models.BooleanField(
                        default=False,
                        help_text='De patient heeft aangegeven zelf geen polikliniek afspraak nodig te vinden. '
                                  'Wilt u op basis van de antwoorden en eventuele laboratoriumuitslagen de patient '
                                  'alsnog oproepen?',
                        verbose_name='Patient alsnog oproepen voor afspraak polikliniek')),
                ('report', core.models.EncryptedTextField(
                    help_text='Nb. selecteer eerst de optie(s) hierboven voordat u de tekst wijzigt.')),
                ('created_by',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='healthprofessional.HealthProfessional')),
                ('questionnaire_request',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='questionnaire.QuestionnaireRequest')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, core.models.ModelAuditMixin),
        ),
    ]
