# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 21:54
from __future__ import unicode_literals

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('healthperson', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secretary',
            fields=[
                ('healthperson_ptr',
                 models.OneToOneField(auto_created=True,
                                      on_delete=django.db.models.deletion.CASCADE,
                                      parent_link=True,
                                      primary_key=True,
                                      serialize=False,
                                      to='healthperson.HealthPerson')),
                ('specialism',
                 models.CharField(choices=[(b'gastro_liver_disease',
                                            b'Maag-darm-leverziekten'),
                                           (b'rheumatology',
                                            b'Reumatologie'),
                                           (b'surgery',
                                            b'Chirurgie'),
                                           (b'internal_medicine',
                                            b'Interne geneeskunde'),
                                           (b'orhopedie',
                                            b'Orhopedie')],
                                  max_length=128,
                                  verbose_name='Specialisme')),
            ],
            options={
                'abstract': False,
            },
            bases=(
                'healthperson.healthperson',
                models.Model,
                core.models.ModelAuditMixin),
        ),
    ]
