# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 21:54
from __future__ import unicode_literals

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('healthperson', '0001_initial'),
        ('healthprofessional', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('healthperson_ptr',
                 models.OneToOneField(auto_created=True,
                                      on_delete=django.db.models.deletion.CASCADE,
                                      parent_link=True,
                                      primary_key=True,
                                      serialize=False,
                                      to='healthperson.HealthPerson')),
                ('rc_registration_number', models.CharField(
                    max_length=128, unique=True)),
                ('diagnose',
                 models.CharField(choices=[(b'rheumatoid_arthritis',
                                            b'Reumatoide artritis'),
                                           (b'chron',
                                            b'Ziekte van Crohn'),
                                           (b'colitis_ulcerosa',
                                            b'Colitis Ulcerosa'),
                                           (b'intestinal_transplantation',
                                            b'Dunnedarmtransplantatie')],
                                  max_length=128,
                                  verbose_name='Diagnose')),
                ('excluded_questionnaires',
                 models.TextField(blank=True, null=True)),
                ('regular_control_frequency',
                 core.models.ChoiceOtherField(choices=[(b'never',
                                                        b'Nooit'),
                                                       (b'3_months',
                                                        b'3 maanden'),
                                                       (b'6_months',
                                                        b'6 maanden'),
                                                       (b'12_months',
                                                        b'12 maanden'),
                                                       (b'other',
                                                        b'Anders, vul aantal weken in')],
                                              max_length=128,
                                              verbose_name='Frequentie reguliere controle')),
                ('blood_sample_frequency',
                 core.models.ChoiceOtherField(choices=[(b'sameasregular',
                                                        b'Zelde als freq. regulier controle'),
                                                       (b'3_months',
                                                        b'3 maanden'),
                                                       (b'6_months',
                                                        b'6 maanden'),
                                                       (b'12_months',
                                                        b'12 maanden'),
                                                       (b'other',
                                                        b'Anders, vul aantal weken in')],
                                              max_length=128,
                                              verbose_name='Frequentie bloedprikken')),
                ('last_blood_sample', models.DateField(blank=True, null=True)),
                ('always_clinic_visit',
                 models.CharField(choices=[(b'alwaysclinicvisit',
                                            b'Altijd na invullen vragenlijsten'),
                                           (b'onlyifwanted',
                                            b'Alleen als gewenst of vereist')],
                                  max_length=128,
                                  verbose_name='Volgt altijd een polikliniekbezoek?')),
                ('regular_control_start_notification',
                 models.CharField(choices=[(b'sms_and_email',
                                            b'Zowel per e-mail als per sms'),
                                           (b'sms_only',
                                            b'Alleen per sms'),
                                           (b'email_only',
                                            b'Alleen per e-mail')],
                                  default=b'sms_and_email',
                                  max_length=32,
                                  verbose_name='Starten van een reguliere controle')),
                (
                    'regular_control_reminder_notification',
                    models.CharField(
                        choices=[
                            (b'sms_and_email',
                             b'Zowel per e-mail als per sms'),
                            (b'sms_only',
                             b'Alleen per sms'),
                            (b'email_only',
                             b'Alleen per e-mail')],
                        default=b'sms_and_email',
                        max_length=32,
                        verbose_name='Herinneringen bij een reguliere controle, '
                                     'indien deze niet binnen 1 week is ingevuld.')),
                (
                    'healthprofessional_handling_notification',
                    models.CharField(
                        choices=[
                            (b'sms_and_email',
                             b'Zowel per e-mail als per sms'),
                            (b'sms_only',
                             b'Alleen per sms'),
                            (b'email_only',
                             b'Alleen per e-mail')],
                        default=b'sms_and_email',
                        max_length=32,
                        verbose_name='Uitslag van een controle of "het gaat niet goed" nadat de '
                                     'behandelaar deze heeft beoordeeld en verwerkt.')),
                ('message_notification',
                 models.CharField(choices=[(b'sms_and_email',
                                            b'Zowel per e-mail als per sms'),
                                           (b'sms_only',
                                            b'Alleen per sms'),
                                           (b'email_only',
                                            b'Alleen per e-mail')],
                                  default=b'sms_and_email',
                                  max_length=32,
                                  verbose_name='Overige berichten van een arts of verpleegkundige.')),
                ('current_practitioner',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='healthprofessional.HealthProfessional',
                                   verbose_name='Hoofd-behandelaar')),
            ],
            options={
                'abstract': False,
            },
            bases=(
                'healthperson.healthperson',
                models.Model,
                core.models.ModelAuditMixin),
        ),
    ]
