# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 21:55
from __future__ import unicode_literals

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QOLChronCUQuestionnaire',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                (
                    'hasproblems',
                    models.CharField(
                        choices=[
                            (b'yes',
                             'Ik vul het in'),
                            (b'no',
                             'Dit vul ik liever niet in')],
                        max_length=32,
                        verbose_name='Hieronder en in de volgende stappen kunt u aangeven of u last heeft van '
                                     'praktische, sociale, emotionele of spirituele problemen. Als u dit liever '
                                     'niet invult , kunt u dat hier aangeven.')),
                ('other_problems',
                 models.TextField(blank=True,
                                  null=True,
                                  verbose_name='Andere problemen')),
                (
                    'need_contact',
                    models.CharField(
                        blank=True,
                        choices=[
                            (b'yes',
                             'Ja'),
                            (b'no',
                             'Nee'),
                            (b'maybe',
                             'Misschien')],
                        max_length=32,
                        null=True,
                        verbose_name='Zou u over deze problemen met een deskundige willen praten? (bijvoorbeeld '
                                     'een psycholoog of een maatschappelijk werker)')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, core.models.ModelAuditMixin),
        ),
        migrations.CreateModel(
            name='QOLEmotionalProblem',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='QOLFysicalProblem',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='QOLPracticalProblem',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='QOLSocialProblem',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='QOLSpiritualProblem',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='QOLQuestionnaire',
            fields=[
                ('qolchroncuquestionnaire_ptr',
                 models.OneToOneField(auto_created=True,
                                      on_delete=django.db.models.deletion.CASCADE,
                                      parent_link=True,
                                      primary_key=True,
                                      serialize=False,
                                      to='qol.QOLChronCUQuestionnaire')),
                ('fysical_problems',
                 core.models.ManyToManyField(blank=True,
                                             help_text=b'',
                                             related_name='fysical_problems',
                                             to='qol.QOLFysicalProblem',
                                             verbose_name='Lichamelijke problemen')),
            ],
            options={
                'abstract': False,
            },
            bases=('qol.qolchroncuquestionnaire',),
        ),
        migrations.AddField(
            model_name='qolchroncuquestionnaire',
            name='emotional_problems',
            field=core.models.ManyToManyField(
                blank=True,
                help_text=b'',
                related_name='emotional_problems',
                to='qol.QOLEmotionalProblem',
                verbose_name='Emotionele problemen'),
        ),
        migrations.AddField(
            model_name='qolchroncuquestionnaire',
            name='practical_problems',
            field=core.models.ManyToManyField(
                blank=True,
                help_text=b'',
                related_name='practial_problems',
                to='qol.QOLPracticalProblem',
                verbose_name='Praktische problemen'),
        ),
        migrations.AddField(
            model_name='qolchroncuquestionnaire',
            name='request_step',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='questionnaire.RequestStep'),
        ),
        migrations.AddField(
            model_name='qolchroncuquestionnaire',
            name='social_problems',
            field=core.models.ManyToManyField(
                blank=True,
                help_text=b'',
                related_name='social_problems',
                to='qol.QOLSocialProblem',
                verbose_name='Gezins-/sociale problemen'),
        ),
        migrations.AddField(
            model_name='qolchroncuquestionnaire',
            name='spiritual_problems',
            field=core.models.ManyToManyField(
                blank=True,
                help_text=b'',
                related_name='spiritual_problems',
                to='qol.QOLSpiritualProblem',
                verbose_name='Religieuze/spirituele problemen'),
        ),
    ]
