# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 21:50
from __future__ import unicode_literals

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptionkey',
            name='key',
            field=core.models.EncryptedCharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='user',
            name='BSN',
            field=core.models.EncryptedHMACLookupCharField(
                blank=True,
                max_length=1024,
                null=True,
                verbose_name='Burger Service Nummer'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=core.models.EncryptedHMACLookupEmailField(
                max_length=2048,
                verbose_name='E-mail adres'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=core.models.EncryptedHMACLookupCharField(
                max_length=1024,
                verbose_name='Voornaam'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=core.models.EncryptedHMACLookupCharField(
                max_length=1024,
                verbose_name='Achternaam'),
        ),
        migrations.AlterField(
            model_name='user',
            name='local_hospital_number',
            field=core.models.EncryptedHMACLookupCharField(
                blank=True,
                max_length=1024,
                null=True,
                verbose_name='Lokaal ziekenhuis-nummer'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=core.models.EncryptedCharField(
                max_length=1024,
                verbose_name='Mobiel telefoonnummer'),
        ),
    ]
