# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 21:55
from __future__ import unicode_literals

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishQuestionnaire',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                (
                    'appointment',
                    models.CharField(
                        choices=[
                            (b'no',
                             'Nee, dat hoeft niet'),
                            (b'yes_phone_nurse',
                             'Ja, graag een telefonische afspraak met de gespecialiseerd verpleegkundige'),
                            (b'yes_phone_doctor',
                             'Ja, graag een telefonisch afspraak met de arts'),
                            (b'yes_nurse',
                             'Ja, graag een afspraak op de polikliniek met de gespecialiseerd verpleegkundige'),
                            (b'yes_doctor',
                             'Ja, graag een afspraak op de polikliniek met de arts')],
                        max_length=32,
                        verbose_name='Wilt u, naast deze digitale conrole, graag een afspraak?')),
                ('appointment_period',
                 models.CharField(blank=True,
                                  choices=[(b'within_4_weeks',
                                            'Binnen 4 weken'),
                                           (b'within_2_weeks',
                                            'Binnen 2 weken'),
                                           (b'this_week',
                                            'Deze week')],
                                  max_length=32,
                                  null=True,
                                  verbose_name='Op welke termijn zou u deze afspraak willen?')),
                ('appointment_preference',
                 core.models.ChoiceOtherField(blank=True,
                                              choices=[(b'None',
                                                        'Maakt niet uit'),
                                                       (b'other',
                                                        'Ja, dat wil ik graag aangegeven')],
                                              max_length=512,
                                              null=True,
                                              verbose_name='Heeft u voorkeur voor een dag, periode of tijdstip?')),
                (
                    'blood_sample',
                    core.models.ChoiceOtherField(
                        choices=[
                            (b'umcg',
                             'UMCG'),
                            (b'martini_ziekenhuis',
                             'Martini Ziekenhuis'),
                            (b'lab_noord',
                             'Lab Noord'),
                            (b'other',
                             'Anders')],
                        help_text='Indien u dit nog niet heeft gedaan, wilt u dan de controle opslaan '
                                  'en pas afronden nadat u bloed heeft geprikt?',
                        max_length=128,
                        verbose_name='Waar heeft u bloed laten prikken?')),
                ('blood_sample_date',
                 core.models.DateField(blank=True,
                                       null=True,
                                       verbose_name='Wanneer heeft u bloed laten prikken?')),
                ('request_step',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='questionnaire.RequestStep')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, core.models.ModelAuditMixin),
        ),
        migrations.CreateModel(
            name='StartQuestionnaire',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('current_status',
                 models.CharField(choices=[(b'good',
                                            'Goed'),
                                           (b'less_good',
                                            'Iets minder goed'),
                                           (b'bad',
                                            'Slecht'),
                                           (b'really_bad',
                                            'Erg slecht'),
                                           (b'terrible',
                                            'Afschuwelijk')],
                                  max_length=32,
                                  verbose_name='Hoe gaat het met u?')),
                ('problems', models.TextField(
                    verbose_name='Kunt u hieronder beschrijven hoe het met u gaat en waar u op '
                                 'dit moment het meeste last van heeft?')),
                (
                    'problem_severity',
                    models.IntegerField(
                        choices=[
                            (1,
                             1),
                            (2,
                             2),
                            (3,
                             3),
                            (4,
                             4),
                            (5,
                             5),
                            (6,
                             6),
                            (7,
                             7),
                            (8,
                             8),
                            (9,
                             9),
                            (10,
                             10)],
                        verbose_name='Hoe veel last heeft u van problemen, klachten of zorgen? Dit gaat zowel om de '
                                     'lichamelijke klachten die u ondervindt van uw ziekte als emotionele, sociale of '
                                     'praktische problemen. (1=geen klachten of problemen,10=heel veel klachten of '
                                     'problemen)')),
                (
                    'hospital_visit',
                    models.CharField(
                        choices=[
                            (b'no',
                             'Nee'),
                            (b'yes_urgent_care',
                             'Ja, op de spoedopvang'),
                            (b'yes_intestional_clinic',
                             'Ja, op de polikliniek Maag-darm-leverziekten'),
                            (b'yes_other_specialist',
                             'Ja, bij een andere medisch specialist')],
                        max_length=32,
                        verbose_name='Bent u sinds de vorige controle nog in het ziekenhuis geweest?')),
                ('request_step',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='questionnaire.RequestStep')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, core.models.ModelAuditMixin),
        ),
        migrations.CreateModel(
            name='StartUrgentQuestionnaire',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('appointment_period',
                 models.CharField(choices=[(b'tomorrow',
                                            'Morgen'),
                                           (b'within_3_days',
                                            'Binnen 3 dagen'),
                                           (b'this_week',
                                            'Deze week')],
                                  max_length=32,
                                  verbose_name='Op welke termijn zou u deze afspraak willen?')),
                ('request_step',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='questionnaire.RequestStep')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, core.models.ModelAuditMixin),
        ),
        migrations.CreateModel(
            name='UrgentProblemQuestionnaire',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('problems', models.TextField(
                    verbose_name='Kunt u hieronder beschrijven hoe het met u gaat en waar u op dit '
                                 'moment het meeste last van heeft?')),
                (
                    'problem_severity',
                    models.IntegerField(
                        choices=[
                            (1,
                             1),
                            (2,
                             2),
                            (3,
                             3),
                            (4,
                             4),
                            (5,
                             5),
                            (6,
                             6),
                            (7,
                             7),
                            (8,
                             8),
                            (9,
                             9),
                            (10,
                             10)],
                        verbose_name='Hoe veel last heeft u van problemen, klachten of zorgen? Dit gaat zowel '
                                     'om de lichamelijke klachten die u ondervindt van uw ziekte als emotionele, '
                                     'sociale of praktische problemen. (1=geen klachten of problemen,10=heel veel '
                                     'klachten of problemen)')),
                ('request_step',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='questionnaire.RequestStep')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, core.models.ModelAuditMixin),
        ),
    ]
